### ISSUE TITLE
eslint-loader校验vue中js代码发现的问题

### ISSUE THREAD

**Issue by 363797271** [lagoufed/fed-e-001#2]
## 正在学习的内容

当前刚做完模块02-02的作业

## 问题

本作业一开始将eslint-loader同babel-loader放在同一个rule下：

```js
{
  test: '/\.js$/',
  exclude: /node_modules/,
  use: [
    'babel-loader',
    'eslint-loader'
  ]
},
{
  test: /\.vue$/,
    use: [
      'vue-loader',
    ]
}
```

理论上eslint-loader应该可以校验vue-loader处理vue文件获得的js代码。

但是结果并没有。又采取了以下方案:

1. 去掉exclude（虽然babel编译报错，但eslint还是没有校验）

2. 为eslint-loader单独写一个rule，依然无效（代码中exclude和enforce写不写都无效）

   ```js
   {
     test: /\.js$/,
     use: [
       'eslint-loader',
     ],
     // exclude: /node_modules/,
     // enforce: 'pre',
   },
   ```

最终没有找到原因，老老实实的给vue匹配加了个rule

```js
{
  test: /\.vue$/,
  use: [
    'eslint-loader',
  ],
  enforce: 'pre' // 必须加，保证编译前执行
},
```

## 希望搞清楚

根据文档介绍vue-loader会拷贝rules，对解析的js代码执行匹配的rule，为什么eslint-loader直接配置在js的rule下不生效，必须配置在vue下，希望老师解惑

## 源码地址
https://gitee.com/usaliva/case001/tree/master
错误代码：
```js
// src/App.vue

// ！！！语法错误代码！！！
// aaa
```

**Comment by zce** [comment]
首先给你一个大大的👍，因为通过你的代码，我看到了你尝试解决问题的思路，非常合理。

> 因为当我尝试新建一个 my-loader.js 的时候，发现你的项目中已经有了，哈哈

然后回到正题上来，正如你所说的，`VueLoaderPlugin` 的作用就是拷贝其他 Loader 的配置，使得 vue SFC 文件中的 JS、CSS、SCSS 之类的语法也可被 Loader 处理。

所以你的第一个想法并没有任何问题。

但是在 VueLoaderPlugin 插件的源码中，我发现，它选择性的忽略掉了 eslint-loader：

https://github.com/vuejs/vue-loader/blob/d5f7e16570c83b74019d435b4b47a5a21431699e/lib/loaders/pitcher.js#L16-L28

具体的原因可以参考这一次提交：https://github.com/vuejs/vue-loader/commit/6f1d404c7893ffb790e02c2341b6c7b8e30c7394#diff-649d455a9ef8a5954bc36f0f023e454a

以及所对应的 Issue：https://github.com/vuejs/vue-loader/issues/1359

忍不住还想夸夸你，哈哈哈

**Comment by 363797271** [comment]
谢谢老师！讲的详细又科学！！
隐约觉得vue-loader偷偷跳过了eslint-loader，但是就不知道怎么确认和寻找，代码再往深了看就懵了。
通过老师的解答又学习到可以去issues中搜索问题，之前只在百度搜索，受益良多，感谢感谢！！！
